server:
  port: 8082
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "http://localhost:3001"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
      routes:
        - id: empleado-service
          uri: http://localhost:8083
          predicates:
            - Path=/empleado/**
        - id: marcaje-service
          uri: http://localhost:8086
          predicates:
            - Path=/marcaje/**
        - id: autorizacion-service
          uri: http://localhost:8084
          predicates:
            - Path=/autorizacion/**
        - id: justificativo-service
          uri: http://localhost:8085
          predicates:
            - Path=/justificativo/**
        - id: oficinaRRHH-service
          uri: http://localhost:8087
          predicates:
            - Path=/sueldos/**
keycloak:
  realm: Mueblestgo-realm
  auth-server-url: http://0.0.0.0:8080
  resource: springboot-keycloak
  public-client: true
  bearer-only: true
  use-resource-role-mappings: true
