server:
  port: 8082
spring:
  cloud:
    gateway:
      routes:
        - id: empleado-service
          uri: http://localhost:8083
          predicates:
            - Path=/empleado/**
        - id: marcaje-service
          uri: http://localhost:8086
          predicates:
            - Path=/marcaje/**
        - id: autorizacion-service
          uri: http://localhost:8084
          predicates:
            - Path=/autorizacion/**
