server:
  port: 8082
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
      routes:
        - id: empleado-service
          uri: http://empleados-service:8083
          predicates:
            - Path=/empleado/**
        - id: marcaje-service
          uri: http://marcajes-service:8086
          predicates:
            - Path=/marcaje/**
        - id: autorizacion-service
          uri: http://autorizaciones-service:8084
          predicates:
            - Path=/autorizacion/**
        - id: justificativo-service
          uri: http://justificativos-service:8085
          predicates:
            - Path=/justificativo/**
        - id: oficinaRRHH-service
          uri: http://oficinarrhh-service:8087
          predicates:
            - Path=/sueldos/**
