server:
  port: 8087
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/MSTGO_OficinaRRHH
    username: root
    password: password&1234
  jpa:
    hibernate:
      ddl-auto: update
management:
  endpoints:
    web:
      exposure:
        include: "*"
keycloak:
  realm: Mueblestgo-realm
  auth-server-url: http://0.0.0.0:8080
  resource: springboot-keycloak
  public-client: true
  bearer-only: true
